---
dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8-dev'

matrix:
  allow_failures:
    - python: '3.8-dev'
 
before_install: pip install -U pip coveralls
install: pip install .[testing]
script: pytest --cov styled_components styled_components tests
after_success: coveralls
